// Code generated by hertz generator.

package person

import (
	"context"
	"github.com/cloudwego/hertz/pkg/common/hlog"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	person "hertz-m/biz/model/hertz/person"
)

// PersonInfo .
// @router /person_info/:age [POST]
func PersonInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req person.PersonReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	hlog.Info("PersonInfo log")

	resp := new(person.PersonResp)
	resp.Name = req.Name
	resp.Age = req.Age * 2
	resp.City = "China" + req.City

	c.JSON(consts.StatusOK, resp)
}

// PersonList .
// @router /list [POST]
func PersonList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req person.PersonReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(person.PersonListResp)
	resp.Name = req.Name

	c.JSON(consts.StatusOK, resp)
}
