// Code generated by hertz generator.

package Person

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	fmt.Printf("root middleware \n")
	// your code...
	return nil
}

func _person_infoMw() []app.HandlerFunc {
	fmt.Printf("group middleware \n")
	// your code...
	return nil
}

func _personinfoMw() []app.HandlerFunc {
	fmt.Printf("router middleware \n")
	// your code...
	return nil
}

func _personlistMw() []app.HandlerFunc {
	fmt.Printf("list middleware \n")
	// your code...
	return nil
}
